"""empty message

Revision ID: 7ab8fbee1fdd
Revises: 
Create Date: 2026-04-16 02:04:22.475067

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ab8fbee1fdd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('aggregate_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_outbox_aggregate_id', 'outbox_messages', ['aggregate_id'], unique=False)
    op.create_index('ix_outbox_attempts', 'outbox_messages', ['attempts'], unique=False)
    op.create_index('ix_outbox_event_type', 'outbox_messages', ['event_type'], unique=False)
    op.create_index('ix_outbox_pending_only', 'outbox_messages', ['id', 'created_at'], unique=False, postgresql_where=sa.text('published_at IS NULL'))
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('payment_metadata', sa.JSON(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('webhook_url', sa.String(length=500), nullable=False),
    sa.Column('idempotency_key', sa.String(length=500), nullable=False),
    sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_payments_processed_at', 'payments', ['processed_at'], unique=False)
    op.create_index('ix_payments_status', 'payments', ['status'], unique=False)
    op.create_index('ix_payments_status_processed', 'payments', ['status', 'processed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payments_status_processed', table_name='payments')
    op.drop_index('ix_payments_status', table_name='payments')
    op.drop_index('ix_payments_processed_at', table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_outbox_pending_only', table_name='outbox_messages', postgresql_where=sa.text('published_at IS NULL'))
    op.drop_index('ix_outbox_event_type', table_name='outbox_messages')
    op.drop_index('ix_outbox_attempts', table_name='outbox_messages')
    op.drop_index('idx_outbox_aggregate_id', table_name='outbox_messages')
    op.drop_table('outbox_messages')
    # ### end Alembic commands ###
